"""Announcements

Revision ID: 06739d462f99
Revises: bfdcf33554e9
Create Date: 2025-07-30 13:26:15.620836

"""
from alembic import op
import sqlalchemy as sa

import queer_bristol.database


# revision identifiers, used by Alembic.
revision = '06739d462f99'
down_revision = 'bfdcf33554e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('posted', queer_bristol.database.UTCDateTime(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index('ix_announcement_posted', ['posted'], unique=False, postgresql_using='brin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index('ix_announcement_posted', postgresql_using='brin')

    op.drop_table('announcement')
    # ### end Alembic commands ###
