"""Create group and event models

Revision ID: 477919c5359a
Revises: 
Create Date: 2025-07-23 14:30:12.275185

"""
from alembic import op
import sqlalchemy as sa
import queer_bristol.database

# revision identifiers, used by Alembic.
revision = '477919c5359a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start', queer_bristol.database.UTCDateTime(), nullable=False),
    sa.Column('end', queer_bristol.database.UTCDateTime(), nullable=True),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_slug'))

    op.drop_table('group')
    op.drop_table('event')
    # ### end Alembic commands ###
