"""Create group tags

Revision ID: 6071e9280968
Revises: 477919c5359a
Create Date: 2025-07-24 12:17:22.190371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6071e9280968'
down_revision = '477919c5359a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('event_group_id_fkey', 'group', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(), server_default='', nullable=False))
        batch_op.create_index('ix_group_tags', [sa.literal_column("to_tsvector('english', lower(tags))")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index('ix_group_tags', postgresql_using='gin')
        batch_op.drop_column('tags')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('event_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
