"""Create search vector for Group

Revision ID: ca4aa4cf0310
Revises: 6071e9280968
Create Date: 2025-07-24 13:51:00.602139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca4aa4cf0310'
down_revision = '6071e9280968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', name), 'A') || setweight(to_tsvector('english', tags), 'B') || setweight(to_tsvector('english', description), 'C')", persisted=True), nullable=False))
        batch_op.drop_index(batch_op.f('ix_group_tags'), postgresql_using='gin')
        batch_op.create_index('ix_group_tags', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index('ix_group_tags', postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_group_tags'), [sa.literal_column("to_tsvector('english'::regconfig, lower(tags::text))")], unique=False, postgresql_using='gin')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
